export default [
  { ignores: ["scripts/vendor/**", "tools/**", "**/*.mjs"] },
  {
    files: ["scripts/**/*.js"],
    languageOptions: { ecmaVersion: 2021, sourceType: "script", globals: {
          "window": "readonly",
          "document": "readonly",
          "console": "readonly",
          "setTimeout": "readonly",
          "clearTimeout": "readonly",
          "navigator": "readonly",
          "location": "readonly",
          "fetch": "readonly",
          "FormData": "readonly",
          "CSS": "readonly",
          "Event": "readonly",
          "SpeechSynthesisUtterance": "readonly",
          "speechSynthesis": "readonly",
          "webkitSpeechRecognition": "readonly",
          "SpeechRecognition": "readonly",
          "alert": "readonly",
          "requestAnimationFrame": "readonly",
          "getComputedStyle": "readonly",
          "module": "readonly",
          "CRITERES_2GT": "writable",
          "CRITERES_SUR_PLACE": "writable",
          "DISTANCES_CORBEIL_ESSONNES": "writable",
          "DOMAINS": "writable",
          "DUREES_TRANSPORT_CORBEIL": "writable",
          "LYCEES_2GT": "writable",
          "MAX_BOUTONS": "writable",
          "MOTS_STRUCTURE": "writable",
          "MOTS_VIDES": "writable",
          "NORMALIZED_DISTANCES_CORBEIL": "writable",
          "NORMALIZED_DUREES_CORBEIL": "writable",
          "NO_WORDS": "writable",
          "QUIZ_PRO": "writable",
          "REGLE_FILET_SECURITE": "writable",
          "REGLE_MAX_DEUX_OPTIONS": "writable",
          "REGLE_VOEUX_EXCLUSIFS": "writable",
          "SERIES_TECHNO_2GT": "writable",
          "SEUIL_CONFIANCE": "writable",
          "SOURCE_2GT": "writable",
          "SpeechRecognitionAPI": "writable",
          "TOUS_MOTS_STRUCTURE": "writable",
          "TrouveTaVoie2GT": "writable",
          "VOCABULAIRE": "writable",
          "YES_WORDS": "writable",
          "calculerResultatQuiz": "writable",
          "domainesSurs": "writable",
          "normalize": "writable",
          "pingStats": "writable",
          "pistesProches": "writable",
          "retirerMotsStructure": "writable",
          "startMenu": "writable",
          "telechargerPDF": "writable"
    } },
    // no-undef attrape les affectations à une variable jamais déclarée — c'est
    // exactement le bug "body is not defined" qui a cassé le 2GT en production
    // sans que les tests jsdom (non stricts) le voient.
    rules: { "no-undef": "error" }
  }
];
